name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set PowerShell Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
