name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Terraform
      run: |
        cd C:\Windows\system32
        Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/latest/terraform_$(curl -s https://releases.hashicorp.com/terraform/ | grep -oP '(?<=terraform_)[0-9]+\.[0-9]+\.[0-9]+(?=</a>)' | head -1)_windows_amd64.zip" -OutFile "terraform.zip"
        Expand-Archive terraform.zip -DestinationPath $env:TEMP
        Move-Item "$env:TEMP\terraform.exe" "C:\terraform.exe"

    - name: Terraform Init
      run: |
        C:\terraform.exe init
        
