name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    
     steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set PowerShell Execution Policy
    - name: Set PowerShell Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init
      shell: powershell
      run: terraform init

    - name: Terraform Format
      shell: powershell
      run: terraform fmt -check

    - name: Terraform Plan
      shell: powershell
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      shell: powershell
      run: terraform apply -auto-approve -input=false
